export enum RedisKeys {
  USERS_LIST = "users",
  USER_BY_ID = "user:${userId}",
  USER_BY_USERNAME = "user|username:${username}",
  USERS_BY_ROLE_ID = "users|role:${roleId}",
  USERS_COUNT = "users_count",
  MENUS = "menus",
  MENU_BY_ID = "menu:${menuId}",
  PASSWORD_POLICIES = "password_policies",
  PASSWORD_POLICY_BY_ID = "password_policy:${passwordPolicyId}",
  ROLES = "roles",
  ROLE_BY_ID = "role:${roleId}",
  ACTIVE_ROLES = "roles|active",
  ROLES_COUNT = "roles|count",
  ROLES_LIST = "roles|limit:${pageSize}",
  ACCESS_LIST_BY_ROLE_ID = "access_list|role:${roleId}",
  DEFAULT_ACCESS_LIST = "default_access_list",
  COMBINED_ACCESS_BY_ROLE_ID = "combined_access|role:${roleId}",
  TENANTS = "tenants",
  PROJECTS = "projects",
  TENANT_BY_ID = "tenant:${tenantId}",
  FORM_BUILDERS = "formBuilders",
}
